const Ingredients = require("../models/ingredientsModel.js")

Ingredients.bulkCreate([
  { Name: "Asparagus" },
  { Name: "Broccoli" },
  { Name: "Carrots" },
  { Name: "Cauliflower" },
  { Name: "Celery" },
  { Name: "Corn" },
  { Name: "Cucumbers" },
  { Name: "Lettuce " },
  { Name: "Mushrooms" },
  { Name: "Onions" },
  { Name: "Peppers" },
  { Name: "Potatoes" },
  { Name: "Spinach" },
  { Name: "Squash" },
  { Name: "Zucchini" },
  { Name: "Tomatoes" },
  { Name: "Fresh fruits" },
  { Name: "Apples" },
  { Name: "Avocados" },
  { Name: "Bananas" },
  { Name: "Berries" },
  { Name: "Cherries" },
  { Name: "Grapefruit" },
  { Name: "Grapes" },
  { Name: "Kiwis" },
  { Name: "Melon" },
  { Name: "Oranges" },
  { Name: "Peaches" },
  { Name: "Nectarines" },
  { Name: "Pears" },
  { Name: "Plums" },
  { Name: "Bagels" },
  { Name: "Chip dip" },
  { Name: "English muffins" },
  { Name: "Eggs / Fake eggs" },
  { Name: "Fruit juice" },
  { Name: "Hummus" },
  { Name: "Ready-bake breads" },
  { Name: "Tofu" },
  { Name: "Tortillas" },
  { Name: "Burritos" },
  { Name: "Fish sticks" },
  { Name: "Ice cream" },
  { Name: "Sorbet" },
  { Name: "Popsicles" },
  { Name: "Fries" },
  { Name: "BBQ sauce" },
  { Name: "Gravy" },
  { Name: "Honey" },
  { Name: "Hot sauce" },
  { Name: "Jam" },
  { Name: "Ketchup" },
  { Name: "Mustard" },
  { Name: "Mayonnaise" },
  { Name: "Relish" },
  { Name: "Salad dressing" },
  { Name: "Salsa" },
  { Name: "Soy sauce" },
  { Name: "Steak sauce" },
  { Name: "Syrup" },
  { Name: "Worcestershire sauce" },
  { Name: "Bouillon cubes" },
  { Name: "Cereal" },
  { Name: "Coffee" },
  { Name: "Lemons" },
  { Name: "Limes" },
  { Name: "Olive oil" },
  { Name: "Pancake Mix" },
  { Name: "Waffle mix" },
  { Name: "Pasta" },
  { Name: "Peanut butter" },
  { Name: "Pickles" },
  { Name: "Rice" },
  { Name: "Tea" },
  { Name: "Vegetable oil" },
  { Name: "Vinegar" },
  { Name: "Applesauce" },
  { Name: "Baked beans" },
  { Name: "Chili" },
  { Name: "Fruit" },
  { Name: "Olives" },
  { Name: "Tinned meats" },
  { Name: "Canned Tuna" },
  { Name: "Veggies" },
  { Name: "Basil" },
  { Name: "Black pepper" },
  { Name: "Cilantro" },
  { Name: "Cinnamon" },
  { Name: "Garlic" },
  { Name: "Ginger" },
  { Name: "Mint" },
  { Name: "Oregano" },
  { Name: "Paprika" },
  { Name: "Parsley" },
  { Name: "Red pepper" },
  { Name: "Salt" },
  { Name: "Spice mix" },
  { Name: "Vanilla extract" },
  { Name: "Butter" },
  { Name: "Margarine" },
  { Name: "Cottage cheese" },
  { Name: "Milk" },
  { Name: "Sour cream" },
  { Name: "Whipped cream" },
  { Name: "Yogurt" },
  { Name: "Cheese" },
  { Name: "Bleu cheese" },
  { Name: "Cheddar" },
  { Name: "Cream cheese" },
  { Name: "Feta" },
  { Name: "Goat cheese" },
  { Name: "Mozzarella" },
  { Name: "Parmesan" },
  { Name: "Provolone" },
  { Name: "Ricotta" },
  { Name: "Swiss Cheese" },
  { Name: "Bacon" },
  { Name: "Sausage" },
  { Name: "Beef" },
  { Name: "Chicken" },
  { Name: "Ground beef" },
  { Name: "Turkey" },
  { Name: "Ham" },
  { Name: "Hot dogs, YEAH!" },
  { Name: "Catfish" },
  { Name: "Crab" },
  { Name: "Lobster" },
  { Name: "Mussels" },
  { Name: "Oysters" },
  { Name: "Salmon" },
  { Name: "Shrimp" },
  { Name: "Tilapia" },
  { Name: "Tuna" },
  { Name: "Cod" },
  { Name: "Beer" },
  { Name: "Club soda" },
  { Name: "Champagne" },
  { Name: "Gin" },
  { Name: "Juice" },
  { Name: "Mixers" },
  { Name: "Red wine" },
  { Name: "White wine" },
  { Name: "Rum" },
  { Name: "Saké" },
  { Name: "Soda pop" },
  { Name: "Sports drink" },
  { Name: "Whiskey" },
  { Name: "Vodka" },
  { Name: "Croissants" },
  { Name: "Buns" },
  { Name: "Cake" },
  { Name: "Cookies" },
  { Name: "Donuts" },
  { Name: "Fresh bread" },
  { Name: "Sliced bread" },
  { Name: "Pie! Pie! Pie!" },
  { Name: "Pita bread" },
  { Name: "Baking powder" },
  { Name: "Baking soda" },
  { Name: "Bread crumbs" },
  { Name: "Cake Mix" },
  { Name: "Chocolate chips" },
  { Name: "Cocoa" },
  { Name: "Flour" },
  { Name: "Sugar" },
  { Name: "Sugar substitute" },
  { Name: "Yeast" },
  { Name: "Crackers" },
  { Name: "Dried fruit" },
  { Name: "Granola bars" },
  { Name: "Nuts" },
  { Name: "Seeds" },
  { Name: "Oatmeal" },
  { Name: "Popcorn" },
  { Name: "Potato chips" },
  { Name: "Pretzels" },
])
